"""Revision of Paper_Robustness_WIECON_2026_REVISED.docx per audit.

Tier-1/Tier-2 edits: abstract/intro reframing (audit #1), scope wording (#4),
perturbation justification + refs (#6), alternatives discussion (#7), bootstrap
CIs (#5), MCE/ACE (#12), merged sections (#10), sample-size grounding (#13),
deployment framework (#9, #15), honest limitations (#2, #3), dropped AUC fig,
merged horizon tables, refreshed figures.
"""
import copy
import docx
from docx.shared import Inches
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
from docx.text.paragraph import Paragraph
from docx.enum.text import WD_ALIGN_PARAGRAPH

SRC = "paper/Paper_Robustness_WIECON_2026_REVISED.docx"
FIG = "figs"

d = docx.Document(SRC)
paras = d.paragraphs


def find(substr):
    for p in d.paragraphs:
        if substr in p.text:
            return p
    raise KeyError(substr)


def set_text(p, text):
    img_els = [r._element for r in p.runs if r._element.findall(".//" + qn("a:blip"))]
    text_runs = [r for r in p.runs if r._element not in img_els]
    if text_runs:
        text_runs[0].text = text
        for r in text_runs[1:]:
            r._element.getparent().remove(r._element)
    elif not img_els:
        p.add_run(text)


def append_text(p, text):
    if p.runs:
        p.runs[-1].text += text
    else:
        p.add_run(text)


def insert_after(p, text):
    new_el = OxmlElement("w:p")
    ppr = p._element.find(qn("w:pPr"))
    if ppr is not None:
        new_el.insert(0, copy.deepcopy(ppr))
    p._element.addnext(new_el)
    np = Paragraph(new_el, p._parent)
    if text:
        np.add_run(text)
    return np


def delete(p):
    p._element.getparent().remove(p._element)


def delete_caption_and_table(caption_substr):
    body = d.element.body
    els = list(body.iterchildren())
    for i, el in enumerate(els):
        if el.tag == qn("w:p") and caption_substr in "".join(el.itertext()):
            for j in range(i + 1, len(els)):
                if els[j].tag == qn("w:tbl"):
                    els[j].getparent().remove(els[j])
                    break
            el.getparent().remove(el)
            return
    raise KeyError("caption not found: " + caption_substr)


# --------------------------------------------------------------------------
# 1. Abstract (#1)
set_text(find("Abstract—"), "Abstract— Multihorizon hazard learning produces calibrated "
    "failure probabilities for operational battery reliability, but existing validation uses "
    "only clean laboratory cycling data, leaving calibration quality under operational "
    "distribution shift uncharacterized. We present a systematic robustness evaluation of a "
    "multihorizon hazard model (XGBoost with isotonic calibration, NASA 18650 cells) under "
    "approximate operational conditions generated by synthetic perturbation: partial cycling "
    "(15–100% depth of discharge), temperature noise (σ = 0.5–3.0 °C), and rest irregularity, "
    "at four severity levels. For the investigated model and dataset, the fixed model’s "
    "expected calibration error (ECE) rises from 0.23–0.41 (clean) to 0.28–0.56 (perturbed), "
    "saturating at the mildest severity; maximum calibration error (MCE) and adaptive "
    "calibration error (ACE) confirm the pattern. Recalibration on a 10% operational sample "
    "(≈16 cycles) restores ECE to 0.13–0.20, a 38–76% reduction, with 95% bootstrap "
    "confidence intervals excluding zero and large effect sizes. We conclude that the "
    "calibration layer is the weak point under shift, and we position lightweight "
    "recalibration as a deployment framework for battery failure intelligence.")

# 2. Introduction (#1)
set_text(find("But the model was trained exclusively"),
    "The published multihorizon hazard framework [28] reformulates battery prognostics as "
    "operational reliability estimation: instead of predicting lifetime, it estimates the "
    "probability of failure within service horizons H ∈ {10, 20, 30, 50} cycles and applies "
    "isotonic regression to obtain trustworthy risk probabilities for dispatch decisions. In "
    "cross-validated laboratory experiments, this framework reduced operational failure rates "
    "from 10.3% to 2.95%. Those experiments, however, used clean laboratory data: full cycles "
    "at fixed C-rates, consistent rest periods, and controlled temperatures. Real battery "
    "energy storage systems (BESSs) are dispatched with partial cycles at varying depths of "
    "discharge (DoD), irregular loads and rest periods, and temperature fluctuations. Whether "
    "calibrated failure probabilities survive this distribution shift is unknown, and no "
    "operator can trust a model whose reliability degrades in uncharacterized ways.")
insert_after(find("uncharacterized ways."),
    "This paper contributes: (1) the first systematic robustness evaluation of multihorizon "
    "hazard models under approximate operational conditions, using a synthetic perturbation "
    "methodology at four severity levels; (2) a full characterization of calibration "
    "degradation—ECE, MCE, and ACE—across four horizons, including bootstrap confidence "
    "intervals for recalibration recovery; (3) an operational boundary map and a practical "
    "recalibration deployment strategy requiring no base-model retraining; and (4) causal "
    "evidence, via a Vmin-only ablation, that the minimum-voltage shift is the dominant "
    "failure mechanism. Results are reported for the investigated XGBoost model on the "
    "evaluated NASA dataset; generalization to other chemistries and architectures remains "
    "open (Section 5.4).")

# 3. Related work: SOH/RUL (#1) and calibration (#7), keep Figure 1 image
set_text(find("Battery health prognostics has predominantly"),
    "Battery health prognostics has focused on state-of-health (SOH) estimation and remaining "
    "useful life (RUL) prediction with data-driven models; comprehensive surveys [1], [2] "
    "catalogue mechanisms and methods, most validated on held-out splits of single laboratory "
    "datasets. Recent work covers deep SOH estimation without additional degradation "
    "experiments [3], optimized XGBoost for capacity degradation [4], deep architectures on "
    "NASA data [5], deep-learning reviews with case studies [6], RUL from discharge fragments "
    "[7], feature-engineered deep models [8], impedance-spectroscopy features [9], joint "
    "SOH/RUL prediction from single-cycle charging data [10], and transfer learning under "
    "fast charging [11], [12]. None characterize performance under operational distribution "
    "shift—the gap this paper addresses.")
set_text(find("calibration in machine learning is a distinct"),
    "Probability calibration maps classifier scores to probabilities via Platt scaling [13], "
    "isotonic regression [14], [15], or histogram binning [16]; temperature scaling [17] is "
    "widely used in deep learning. Under distribution shift, model calibration degrades "
    "systematically [18], and calibration data should reflect deployment conditions [19]. "
    "Conformal prediction offers alternative guarantees [20]–[23], distribution-shift "
    "robustness is studied in [24], and domain randomization—training on randomly perturbed "
    "conditions—is a complementary strategy [25], [26]. None of these methods addresses "
    "calibration robustness under operational shift for battery failure models. Figure 1 "
    "illustrates the calibration degradation that motivates this study.")

# 4. Perturbation justification (#6)
append_text(find("Raw discharge curves"),
    " The parameter ranges approximate field operation: partial cycling is the dominant "
    "real-world duty profile, and depth of discharge governs cycle life [29]; σs = 0.5–3.0 °C "
    "is consistent with BESS temperature-sensor accuracy and thermal gradients; and rest "
    "irregularity reflects variable dispatch timing. Because the exact field distribution is "
    "unknown, the severity sweep doubles as a sensitivity analysis of calibration degradation "
    "as conditions deviate progressively from the laboratory baseline.")

# 5. Metrics: MCE/ACE (#12)
append_text(find("Metrics: ECE"),
    " In addition to ECE (10 bins), we report maximum calibration error (MCE) and adaptive "
    "calibration error (ACE, equal-mass bins), which are less sensitive to binning choice [16] "
    "and guard against binning artefacts in the headline ECE results.")

# 6. Table renumbering: 3 -> 2
set_text(find("Table 3: Clean baseline"), "Table 2: Clean baseline (held-out test partition).")

# 7. H = 20 results paragraph (#4, #12)
set_text(find("At H = 20, ECE"),
    "At H = 20, ECE of the frozen model rises from 0.231 on clean held-out data to 0.30–0.32 "
    "under perturbation, a 28–38% increase, while calibrated AUC shifts from 0.594 to "
    "0.57–0.68 (Table 4). Raw (uncalibrated) AUC, which measures rank-ordering independently "
    "of calibration, ranges from 0.52–0.76 under perturbation. MCE (0.31 clean) and ACE "
    "(0.20 clean) confirm the same degradation pattern, ruling out a binning artefact of ECE. "
    "The degradation saturates at Severity 1: even minimal partial cycling causes "
    "near-maximal calibration loss. Temperature scaling, which adjusts only a single logistic "
    "slope, fails to correct this at longer horizons, whereas isotonic and Platt regression "
    "perform similarly across all horizons. Figure 2 shows the saturation across all four "
    "horizons.")

# 8. Full-horizon paragraph (tables 5-7 removed)
set_text(find("The pattern holds across all horizons"),
    "The pattern holds at every horizon, with longer horizons showing higher absolute ECE "
    "both at baseline and under perturbation (0.49–0.54 at H = 50 versus 0.31–0.33 at "
    "H = 10). Saturation is consistent everywhere, and the degradation relative to the "
    "within-horizon clean baseline is most pronounced at H = 20 and H = 50.")

# 9. Sample-size grounding (#13)
append_text(find("Figure 8 examines"),
    " The 10% fraction corresponds to ≈16 of the 163 held-out cycles; the 50–100-cycle "
    "recommendation of Section 5.3 sits on the elbow of this curve and captures most of the "
    "achievable reduction.")

# 10. Recalibration paragraph: bootstrap CIs, effect sizes (#5)
set_text(find("Recalibrating isotonic regression on a 10%"),
    "Recalibrating isotonic regression on a 10% sample of perturbed data recovers "
    "calibration at every horizon: ECE falls from 0.28–0.56 under perturbation to 0.13–0.20, "
    "a 38–76% reduction, with larger reductions at longer horizons (Table 3). A paired "
    "bootstrap with 10 000 resamples over the 20 (severity, seed) conditions per horizon "
    "yields 95% confidence intervals for the ECE reduction of [0.078, 0.168] at H = 10, "
    "[0.135, 0.184] at H = 20, [0.218, 0.275] at H = 30, and [0.364, 0.414] at H = 50, all "
    "excluding zero; rank-biserial correlations range from 0.88 to 1.00 and Cohen’s d_z from "
    "1.2 to 6.7, indicating large and consistent effects. A one-sample Wilcoxon signed-rank "
    "test on the paired differences confirms significance at every horizon (p ≤ 6.7 × 10⁻⁶; "
    "Bonferroni threshold 0.0125). Platt scaling performs equivalently to isotonic regression "
    "across horizons, while temperature scaling underperforms at longer horizons.")

# 11. Table 8 -> 3 caption
p = find("Table 8: Recalibration effectiveness")
p.style = "Normal"
set_text(p, "Table 3: Recalibration effectiveness across all horizons (held-out evaluation "
    "on the same 90% subset, mean ± std across 5 seeds × 4 severities).")

# 12. Ablation/DR references: Table 9 -> 5, Table 10 -> 6
set_text(find("Restoring Vmin alone"), find("Restoring Vmin alone").text.replace("Table 9", "Table 5"))
set_text(find("Domain randomization provides"), find("Domain randomization provides").text.replace("Table 10", "Table 6"))
set_text(find("Figure 7 confirms via SHAP"), find("Figure 7 confirms via SHAP").text.replace("Section 4.5, Table 9", "Table 5"))
set_text(find("Table 9: Vmin-only ablation"), find("Table 9: Vmin-only ablation").text.replace("Table 9:", "Table 5:"))
set_text(find("Table 10:  Domain randomization"), find("Table 10:  Domain randomization").text.replace("Table 10:", "Table 6:"))

# 13. Figure 4 caption (2x2 layout)
set_text(find("Figure 4: Combined robustness summary"),
    "Figure 4: Combined robustness summary at H = 20. (a) Reliability diagram at Severity 1; "
    "(b) ECE across severity levels; (c) AUC across severity levels; (d) summary table of key "
    "metrics. Recalibration consistently reduces ECE across all horizons and severity levels.")

# 14. Root cause paragraph cleanup
set_text(find("The primary driver of calibration degradation"),
    "The primary driver of calibration degradation is the shift in the minimum-voltage "
    "feature. In full discharge, Vmin reaches ≈2.3 V; at 75% DoD truncation (Severity 1, seed "
    "42), it rises to ≈3.2 V, a 37% increase (Figure 6). The shift saturates at Severity 1, "
    "mirroring the ECE saturation pattern, and varies little across seeds. The XGBoost model "
    "learned split thresholds on clean feature ranges, and the isotonic calibrator cannot "
    "adapt to the shifted raw probability distribution.")

# 15. Zones: fold 5.2 into 5.1
append_text(find("Our results define three operating zones:"),
    " Calibration is fragile because the isotonic layer—essential for clean-data "
    "performance—becomes a weak link under shift: rank-ordering is partially retained "
    "(AUC 0.48–0.77), but the probability magnitude becomes unreliable.")

# 16. Figure 7 caption + interaction panel
set_text(find("Figure 7: SHAP summary plots"),
    "Figure 7: SHAP analysis at H = 20. Top: summary plots comparing clean (left) and "
    "perturbed (right) operating conditions; minimum voltage (Vmin) is the dominant feature "
    "in both regimes. Under perturbation, the distribution of every feature shifts, causing "
    "the isotonic calibrator to map shifted raw probabilities to incorrect calibrated values. "
    "Bottom: Vmin interaction magnitudes, showing that the strongest interactions involve "
    "other perturbed features (Vavg, duration).")

# 17. Conclusion
set_text(find("This paper presents the first systematic robustness"),
    "This paper presents the first systematic robustness evaluation of multihorizon battery "
    "failure intelligence under approximate operational conditions. Three principal findings "
    "emerge:")

# 18. Limitations (#2, #3, #4)
set_text(find("Ten limitations should be noted"),
    "Several limitations should be noted. First, the perturbation model approximates "
    "operational conditions—partial cycling, temperature noise, and rest irregularity—but is "
    "not a digital twin of field operation: it does not simulate real-time load-following "
    "profiles, current pulses above 1C, or multi-cell thermal interactions found in "
    "utility-scale BESS deployments. Second, results are reported for LCO chemistry (NASA "
    "18650 cells) and for the investigated XGBoost model; validation across LFP/NMC "
    "chemistries and other architectures is needed. Third, the true SOH trajectory is "
    "preserved throughout, isolating observational shift from coupled degradation dynamics. "
    "Fourth, the Gaussian temperature-noise model does not capture systematic thermal "
    "gradients or diurnal variation. Fifth, the sample-size sweep (Figure 8) tests only the "
    "isotonic calibrator; Platt scaling may respond differently to sample size. Sixth, the "
    "SHAP analysis (Figure 7) is presented for H = 20 at Severity 1 and a single seed; the "
    "Vmin-only ablation (Section 4.5) provides causal evidence across all horizons and seeds, "
    "mitigating this concern. Seventh, the reduction metric (ECEpert − ECErecal)/ECEpert "
    "measures improvement relative to the perturbed state, not recovery toward the clean "
    "baseline; recalibration is most impactful where perturbation created real degradation, "
    "namely H = 20 and H = 50.")

# 19. New references (after [27])
last_ref = find("[27] B. Saha")
p28 = insert_after(last_ref, "[28] Multihorizon hazard learning framework for battery "
    "failure prediction, IEEE WIECON 2026, under review.")
insert_after(p28, "[29] J. Wang, P. Liu, J. Hicks-Garner, E. Sherman, S. Soukiazian, M. "
    "Verbrugge, H. Tataria, J. Musser, and P. Finamore, “Cycle-life model for graphite-LiFePO4 "
    "cells,” Journal of Power Sources, vol. 196, no. 8, pp. 3942–3948, 2011.")

# --------------------------------------------------------------------------
# Deletions
# standalone AUC image paragraph (right before the Figure 3 caption)
for p in list(paras):
    nxt = p._element.getnext()
    if p.text.strip() == "" and p._element.findall(".//" + qn("a:blip")) and \
            nxt is not None and "Figure 3: AUC" in "".join(nxt.itertext()):
        delete(p)
        break
delete(find("Figure 3: AUC vs. severity"))
for sub in ["TABLE 2: Recalibration recovery",
            "Table 5: Result sat H=10",
            "Table 6: Results at H=30",
            "Table 7: Results at H = 50"]:
    delete_caption_and_table(sub)
delete(find("As a further check"))
delete(find("5.2 Why Calibration Is Fragile"))
delete(find("The isotonic regression layer"))

# --------------------------------------------------------------------------
# Image replacement, in document order
new_images = {
    1: ("F_Reliability_Diagrams.png", 3.4),
    2: ("F_ECE_vs_Severity.png", 3.5),
    4: ("F_Combined_Robustness.png", 3.5),
    5: ("F_DR_Comparison.png", 3.5),
    6: ("F_Distribution_Vmin.png", 3.5),
    7: ("F_SHAP_Vmin.png", 3.4),
    8: ("F_Sample_Sweep.png", 3.5),
}
drawn = [p for p in d.paragraphs if p._element.findall(".//" + qn("a:blip"))]
print("REMAINING DRAWING PARAS:")
for _p in drawn:
    nxt = _p._element.getnext()
    nxttxt = "".join(nxt.itertext())[:50] if nxt is not None else "<none>"
    print(f"  blips | text={_p.text[:40]!r} | next={nxttxt!r}")
assert len(drawn) == len(new_images), f"expected {len(new_images)} images, got {len(drawn)}"
for p, (idx, (fname, w)) in zip(drawn, sorted(new_images.items())):
    run = next(r for r in p.runs if r._element.findall(".//" + qn("a:blip")))
    for dr in list(run._element.findall(".//" + qn("w:drawing"))):
        run._element.remove(dr)
    run.add_picture(f"{FIG}/{fname}", width=Inches(w))

# --------------------------------------------------------------------------
# New figures: SHAP interaction before Figure 7 caption; deployment after 5.3
interaction_par = insert_after(find("Figure 7: SHAP analysis at H = 20"), None)
interaction_par.add_run().add_picture(f"{FIG}/F_SHAP_Interaction.png", width=Inches(3.4))
interaction_par.alignment = WD_ALIGN_PARAGRAPH.CENTER

deploy_anchor = find("This requires no base classifier retraining")
deploy_img = insert_after(deploy_anchor, None)
deploy_img.add_run().add_picture(f"{FIG}/F_Deployment_Framework.png", width=Inches(3.4))
deploy_img.alignment = WD_ALIGN_PARAGRAPH.CENTER
insert_after(deploy_img,
    "Figure 9: Calibration-aware deployment framework for multihorizon battery failure "
    "intelligence. The frozen base model is deployed unchanged; a lightweight recalibration "
    "layer (isotonic or Platt) is fitted on a small operational sample and updated "
    "periodically.")
insert_after(find("periodically."),
    "Deployment integration. Recalibration is lightweight: fitting isotonic regression on "
    "tens of samples takes milliseconds on BMS-class hardware and requires no training data "
    "beyond the operational sample (Section 5.5). The 50–100-cycle collection window sits on "
    "the elbow of Figure 8, and because degradation is slow relative to that window, periodic "
    "updates—quarterly, or when a live ECE monitor exceeds 0.20—suffice. This positions "
    "recalibration as a calibration-aware deployment layer over the frozen base model, "
    "consistent with the operational boundary map of Section 5.1.")

# --------------------------------------------------------------------------
# Page size: IEEE Letter, 0.75in margins
for sect in d.sections:
    sect.page_width = Inches(8.5)
    sect.page_height = Inches(11)
    sect.left_margin = Inches(0.75)
    sect.right_margin = Inches(0.75)
    sect.top_margin = Inches(0.75)
    sect.bottom_margin = Inches(0.75)

d.save(SRC)

d2 = docx.Document(SRC)
n_img = len([p for p in d2.paragraphs if p._element.findall(".//" + qn("a:blip"))])
words = sum(len(p.text.split()) for p in d2.paragraphs)
print(f"saved {SRC}")
print(f"tables={len(d2.tables)} (7 data + author expected), images={n_img}, words={words}")
